import { CoDesignParameter } from "./co-design.types";

export class CoDesignParameterEngine {
  public static createDefaultParameters(): Record<string, CoDesignParameter> {
    return {
      // 1. Microarchitecture
      clockFrequencyGhz: {
        parameterId: "clockFrequencyGhz",
        name: "Core Clock Frequency",
        domain: "MICROARCHITECTURE",
        currentValue: 2.85,
        baselineValue: 2.85,
        unit: "GHz",
        minValue: 1.0,
        maxValue: 4.5,
        step: 0.05,
        sourceType: "EMPIRICAL_MEASUREMENT",
        provenance: "Physical Silicon Testbench Clock Telemetry",
        confidence: "HIGH",
        description: "Target sustained GPU core clock frequency under workload load.",
      },
      baseIpc: {
        parameterId: "baseIpc",
        name: "Base Instructions Per Cycle (IPC)",
        domain: "MICROARCHITECTURE",
        currentValue: 2.15,
        baselineValue: 2.15,
        unit: "IPC",
        minValue: 0.5,
        maxValue: 4.0,
        step: 0.05,
        sourceType: "DERIVED_ESTIMATE",
        provenance: "Hardware Execution PMU Trace IPC",
        confidence: "HIGH",
        description: "Average instructions retired per clock cycle across compute shaders.",
      },
      simdVectorWidth: {
        parameterId: "simdVectorWidth",
        name: "SIMD Vector Execution Width",
        domain: "MICROARCHITECTURE",
        currentValue: 32,
        baselineValue: 32,
        unit: "lanes",
        minValue: 16,
        maxValue: 128,
        step: 16,
        sourceType: "EMPIRICAL_MEASUREMENT",
        provenance: "Architectural Specification",
        confidence: "HIGH",
        description: "Execution width of SIMD vector units per compute unit / SM.",
      },
      branchMispredictionPenalty: {
        parameterId: "branchMispredictionPenalty",
        name: "Branch Misprediction Penalty",
        domain: "MICROARCHITECTURE",
        currentValue: 14,
        baselineValue: 14,
        unit: "cycles",
        minValue: 4,
        maxValue: 40,
        step: 1,
        sourceType: "DERIVED_ESTIMATE",
        provenance: "Microarchitectural Model Parameter",
        confidence: "MODERATE",
        description: "Average cycle penalty incurred on pipeline flush following branch misprediction.",
      },

      // 2. Cache Hierarchy
      l1CacheLatencyCycles: {
        parameterId: "l1CacheLatencyCycles",
        name: "L1 Cache Latency",
        domain: "CACHE_HIERARCHY",
        currentValue: 4,
        baselineValue: 4,
        unit: "cycles",
        minValue: 1,
        maxValue: 12,
        step: 1,
        sourceType: "DERIVED_ESTIMATE",
        provenance: "Silicon Microbenchmark Probe",
        confidence: "HIGH",
        description: "L1 Data / Texture Cache load-to-use access latency.",
      },
      l2CacheCapacityMb: {
        parameterId: "l2CacheCapacityMb",
        name: "L2 Cache Capacity",
        domain: "CACHE_HIERARCHY",
        currentValue: 96,
        baselineValue: 96,
        unit: "MB",
        minValue: 16,
        maxValue: 256,
        step: 8,
        sourceType: "EMPIRICAL_MEASUREMENT",
        provenance: "Silicon Hardware Specification",
        confidence: "HIGH",
        description: "Total on-die L2 cache capacity shared across shader engines.",
      },
      l3CacheLatencyCycles: {
        parameterId: "l3CacheLatencyCycles",
        name: "L3 / LLC Cache Latency",
        domain: "CACHE_HIERARCHY",
        currentValue: 38,
        baselineValue: 38,
        unit: "cycles",
        minValue: 15,
        maxValue: 80,
        step: 1,
        sourceType: "DERIVED_ESTIMATE",
        provenance: "Microarchitectural Attribution Model",
        confidence: "MODERATE",
        description: "Last-Level Cache access latency before off-chip memory fallback.",
      },

      // 3. Memory Subsystem
      memoryBandwidthGbps: {
        parameterId: "memoryBandwidthGbps",
        name: "Memory Bandwidth",
        domain: "MEMORY_SUBSYSTEM",
        currentValue: 1792,
        baselineValue: 1792,
        unit: "GB/s",
        minValue: 500,
        maxValue: 3500,
        step: 32,
        sourceType: "EMPIRICAL_MEASUREMENT",
        provenance: "VRAM Interface Hardware Specification (GDDR7 512-bit)",
        confidence: "HIGH",
        description: "Peak theoretical memory subsystem bandwidth to VRAM.",
      },
      memoryLatencyNs: {
        parameterId: "memoryLatencyNs",
        name: "DRAM Memory Access Latency",
        domain: "MEMORY_SUBSYSTEM",
        currentValue: 85,
        baselineValue: 85,
        unit: "ns",
        minValue: 40,
        maxValue: 180,
        step: 5,
        sourceType: "DERIVED_ESTIMATE",
        provenance: "Memory Subsystem Latency Calibration",
        confidence: "MODERATE",
        description: "Round-trip latency to off-chip physical memory.",
      },

      // 4. Interconnect
      pcieBandwidthGbps: {
        parameterId: "pcieBandwidthGbps",
        name: "PCIe Host Interconnect Bandwidth",
        domain: "INTERCONNECT",
        currentValue: 64,
        baselineValue: 64,
        unit: "GB/s",
        minValue: 16,
        maxValue: 128,
        step: 8,
        sourceType: "EMPIRICAL_MEASUREMENT",
        provenance: "PCIe 5.0 x16 Interface",
        confidence: "HIGH",
        description: "Host-to-device bus interface bandwidth capacity.",
      },

      // 5. Software & Runtime
      driverOverheadCyclesPct: {
        parameterId: "driverOverheadCyclesPct",
        name: "Driver & API Overhead",
        domain: "SOFTWARE_RUNTIME",
        currentValue: 5.5,
        baselineValue: 5.5,
        unit: "% of cycles",
        minValue: 1.0,
        maxValue: 25.0,
        step: 0.5,
        sourceType: "DERIVED_ESTIMATE",
        provenance: "DirectX 12 / Driver Kernel Time Profile",
        confidence: "MODERATE",
        description: "Percentage of total frame cycles spent executing driver / runtime API dispatch.",
      },

      // 6. Thermal & Power
      powerLimitWatts: {
        parameterId: "powerLimitWatts",
        name: "Power Limit Cap",
        domain: "THERMAL_POWER",
        currentValue: 500,
        baselineValue: 500,
        unit: "Watts",
        minValue: 150,
        maxValue: 750,
        step: 10,
        sourceType: "EMPIRICAL_MEASUREMENT",
        provenance: "VBIOS Power Limit Setting",
        confidence: "HIGH",
        description: "Configured total board power limit cap.",
      },
      thermalCeilingCelsius: {
        parameterId: "thermalCeilingCelsius",
        name: "Thermal Throttling Ceiling",
        domain: "THERMAL_POWER",
        currentValue: 88,
        baselineValue: 88,
        unit: "°C",
        minValue: 65,
        maxValue: 105,
        step: 1,
        sourceType: "EMPIRICAL_MEASUREMENT",
        provenance: "VBIOS Thermal Throttle Sensor Trip",
        confidence: "HIGH",
        description: "Junction temperature trip point triggering clock and voltage throttling.",
      },
    };
  }

  public static updateParameterValue(
    parameters: Record<string, CoDesignParameter>,
    parameterId: string,
    newValue: number
  ): Record<string, CoDesignParameter> {
    const param = parameters[parameterId];
    if (!param) return parameters;

    const clampedValue = Math.min(param.maxValue, Math.max(param.minValue, newValue));
    return {
      ...parameters,
      [parameterId]: {
        ...param,
        currentValue: clampedValue,
        sourceType: clampedValue === param.baselineValue ? param.sourceType : "HYPOTHETICAL_INTERVENTION",
      },
    };
  }
}
