CREATE TABLE enterprise_system_health (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, tenant_id UUID REFERENCES organizations(id) ON DELETE CASCADE, subsystem TEXT NOT NULL, health_status TEXT DEFAULT 'HEALTHY', latency_ms INTEGER DEFAULT 45, error_rate NUMERIC(5,2) DEFAULT 0.00, last_check_at TIMESTAMPTZ DEFAULT NOW(), status_details JSONB DEFAULT '{}'::jsonb, provenance_hash TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE enterprise_operational_events (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, subsystem TEXT NOT NULL, event_type TEXT NOT NULL, severity TEXT DEFAULT 'INFO', payload JSONB DEFAULT '{}'::jsonb, correlation_id TEXT NOT NULL, provenance_hash TEXT NOT NULL, recorded_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE enterprise_operational_incidents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, title TEXT NOT NULL, incident_type TEXT NOT NULL, severity TEXT DEFAULT 'HIGH', status TEXT DEFAULT 'OPEN', affected_subsystems JSONB DEFAULT '[]'::jsonb, root_cause_hypothesis TEXT, verified_root_cause TEXT, detected_at TIMESTAMPTZ DEFAULT NOW(), resolved_at TIMESTAMPTZ);
CREATE TABLE enterprise_error_records (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, subsystem TEXT NOT NULL, error_code TEXT NOT NULL, error_message TEXT NOT NULL, severity TEXT DEFAULT 'HIGH', is_retryable BOOLEAN DEFAULT false, frequency_count INTEGER DEFAULT 1, correlation_id TEXT NOT NULL, first_seen_at TIMESTAMPTZ DEFAULT NOW(), last_seen_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE enterprise_provider_telemetry (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, provider_name TEXT NOT NULL, model_name TEXT NOT NULL, status TEXT DEFAULT 'HEALTHY', latency_ms INTEGER DEFAULT 320, capacity_status TEXT DEFAULT 'NORMAL', error_classification TEXT, recorded_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE enterprise_operational_dependencies (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, service_name TEXT NOT NULL, dependency_name TEXT NOT NULL, dependency_type TEXT NOT NULL, health_status TEXT DEFAULT 'HEALTHY', criticality TEXT DEFAULT 'HIGH', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE enterprise_reliability_metrics (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, subsystem TEXT NOT NULL, availability_percentage NUMERIC(5,2) DEFAULT 99.95, mttr_seconds INTEGER DEFAULT 45, mttd_seconds INTEGER DEFAULT 10, error_budget_remaining NUMERIC(5,2) DEFAULT 92.5, evaluated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE enterprise_operational_remediations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, incident_id UUID REFERENCES enterprise_operational_incidents(id) ON DELETE CASCADE, proposed_action TEXT NOT NULL, status TEXT DEFAULT 'AI_PROPOSED', phase32_command_id TEXT, phase40_plan_id TEXT, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE enterprise_operational_verifications (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, remediation_id UUID REFERENCES enterprise_operational_remediations(id) ON DELETE CASCADE, expected_state JSONB DEFAULT '{}'::jsonb, observed_state JSONB DEFAULT '{}'::jsonb, verification_status TEXT DEFAULT 'VERIFIED_SUCCESS', verified_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE enterprise_operational_controls (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, subsystem TEXT NOT NULL, maintenance_mode BOOLEAN DEFAULT false, automation_suspended BOOLEAN DEFAULT false, controlled_by TEXT NOT NULL, updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE enterprise_operational_drift (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, subsystem TEXT NOT NULL, drift_type TEXT NOT NULL, drift_level TEXT DEFAULT 'NO_DRIFT', detected_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE enterprise_operational_learning (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, incident_id TEXT, lesson_type TEXT NOT NULL, description TEXT NOT NULL, append_only BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE enterprise_operational_recommendations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, recommendation_type TEXT NOT NULL, title TEXT NOT NULL, rationale TEXT NOT NULL, status TEXT DEFAULT 'AI_PROPOSED', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE enterprise_operational_traces (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, root_event_id TEXT NOT NULL, trace_payload JSONB DEFAULT '{}'::jsonb, provenance_hash TEXT NOT NULL, generated_at TIMESTAMPTZ DEFAULT NOW());
ALTER TABLE enterprise_system_health ENABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise_operational_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise_operational_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise_error_records ENABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise_provider_telemetry ENABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise_operational_dependencies ENABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise_reliability_metrics ENABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise_operational_remediations ENABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise_operational_verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise_operational_controls ENABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise_operational_drift ENABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise_operational_learning ENABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise_operational_recommendations ENABLE ROW LEVEL SECURITY;
ALTER TABLE enterprise_operational_traces ENABLE ROW LEVEL SECURITY;
CREATE INDEX idx_enterprise_system_health_ws ON enterprise_system_health(workspace_id);
CREATE INDEX idx_enterprise_operational_events_ws ON enterprise_operational_events(workspace_id);
CREATE INDEX idx_enterprise_operational_incidents_ws ON enterprise_operational_incidents(workspace_id);
CREATE INDEX idx_enterprise_error_records_ws ON enterprise_error_records(workspace_id);
CREATE INDEX idx_enterprise_provider_telemetry_ws ON enterprise_provider_telemetry(workspace_id);
CREATE INDEX idx_enterprise_operational_dependencies_ws ON enterprise_operational_dependencies(workspace_id);
CREATE INDEX idx_enterprise_reliability_metrics_ws ON enterprise_reliability_metrics(workspace_id);
CREATE INDEX idx_enterprise_operational_remediations_ws ON enterprise_operational_remediations(workspace_id);
CREATE INDEX idx_enterprise_operational_verifications_ws ON enterprise_operational_verifications(workspace_id);
CREATE INDEX idx_enterprise_operational_controls_ws ON enterprise_operational_controls(workspace_id);
CREATE INDEX idx_enterprise_operational_drift_ws ON enterprise_operational_drift(workspace_id);
CREATE INDEX idx_enterprise_operational_learning_ws ON enterprise_operational_learning(workspace_id);
CREATE INDEX idx_enterprise_operational_recommendations_ws ON enterprise_operational_recommendations(workspace_id);
CREATE INDEX idx_enterprise_operational_traces_ws ON enterprise_operational_traces(workspace_id);
