
-- Migration 00054
CREATE TABLE IF NOT EXISTS enterprise_customer_experience (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, tenant_id UUID REFERENCES organizations(id) ON DELETE CASCADE, customer_code TEXT NOT NULL, segment TEXT DEFAULT 'ENTERPRISE', lifecycle_stage TEXT DEFAULT 'ACTIVE', overall_experience_score NUMERIC(5,2) DEFAULT 88.5, retention_status TEXT DEFAULT 'STABLE', provenance_hash TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_context (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, customer_id UUID REFERENCES enterprise_customer_experience(id) ON DELETE CASCADE, tier TEXT DEFAULT 'TIER_1', preferred_channel TEXT DEFAULT 'OMNICHANNEL', sla_tier TEXT DEFAULT 'PLATINUM', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_journeys (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, journey_name TEXT NOT NULL, journey_type TEXT DEFAULT 'ONBOARDING', friction_score NUMERIC(5,2) DEFAULT 14.5, completion_rate_pct NUMERIC(5,2) DEFAULT 94.2, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_journey_stages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, journey_id UUID REFERENCES enterprise_customer_journeys(id) ON DELETE CASCADE, stage_number INTEGER NOT NULL, stage_name TEXT NOT NULL, touchpoint_count INTEGER DEFAULT 3, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_service_cases (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, customer_id UUID REFERENCES enterprise_customer_experience(id) ON DELETE CASCADE, case_number TEXT NOT NULL, category TEXT DEFAULT 'TECHNICAL_SUPPORT', severity TEXT DEFAULT 'HIGH', status TEXT DEFAULT 'RESOLVED', channel TEXT DEFAULT 'PORTAL', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_service_performance (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, first_response_time_minutes NUMERIC(8,2) DEFAULT 12.4, resolution_time_hours NUMERIC(8,2) DEFAULT 4.2, first_contact_resolution_rate_pct NUMERIC(5,2) DEFAULT 82.5, sla_adherence_rate_pct NUMERIC(5,2) DEFAULT 99.1, recorded_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_service_quality (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, case_id UUID REFERENCES enterprise_service_cases(id) ON DELETE CASCADE, quality_score NUMERIC(5,2) DEFAULT 95.0, audit_status TEXT DEFAULT 'VERIFIED_AUDIT', evaluated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_service_defects (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, defect_type TEXT NOT NULL, severity TEXT DEFAULT 'MEDIUM', containment_status TEXT DEFAULT 'CONTAINED', occurred_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_complaints (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, customer_id UUID REFERENCES enterprise_customer_experience(id) ON DELETE CASCADE, complaint_type TEXT NOT NULL, regulatory_sensitivity TEXT DEFAULT 'LOW', status TEXT DEFAULT 'RESOLVED', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_escalations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, case_id UUID REFERENCES enterprise_service_cases(id) ON DELETE CASCADE, escalation_level TEXT DEFAULT 'TIER_3', reason TEXT NOT NULL, status TEXT DEFAULT 'CLOSED', escalated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_voice_of_customer (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, feedback_source TEXT DEFAULT 'SURVEY', feedback_text TEXT NOT NULL, theme TEXT DEFAULT 'USABILITY', sentiment_score NUMERIC(5,2) DEFAULT 84.0, recorded_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_sentiment (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, customer_id UUID REFERENCES enterprise_customer_experience(id) ON DELETE CASCADE, sentiment_category TEXT DEFAULT 'POSITIVE', confidence_score NUMERIC(5,2) DEFAULT 91.5, analyzed_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_effort (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, journey_id UUID REFERENCES enterprise_customer_journeys(id) ON DELETE CASCADE, effort_score NUMERIC(5,2) DEFAULT 2.1, transfer_count INTEGER DEFAULT 0, evaluated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_service_knowledge (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, article_title TEXT NOT NULL, category TEXT DEFAULT 'TROUBLESHOOTING', effectiveness_score NUMERIC(5,2) DEFAULT 89.2, view_count INTEGER DEFAULT 1420, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_service_capacity (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, department_code TEXT DEFAULT 'CUSTOMER_OPS', queue_depth INTEGER DEFAULT 14, agent_utilization_rate NUMERIC(5,2) DEFAULT 78.4, evaluated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_impacts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, service_incident_id TEXT NOT NULL, impacted_customer_count INTEGER DEFAULT 12, revenue_at_risk_usd NUMERIC(14,2) DEFAULT 45000.00, evaluated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_retention (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, customer_id UUID REFERENCES enterprise_customer_experience(id) ON DELETE CASCADE, retention_probability_pct NUMERIC(5,2) DEFAULT 94.5, strategy TEXT DEFAULT 'PROACTIVE_ENGAGEMENT', assessed_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_churn_signals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, customer_id UUID REFERENCES enterprise_customer_experience(id) ON DELETE CASCADE, signal_type TEXT DEFAULT 'USAGE_DROP', severity TEXT DEFAULT 'MEDIUM', confidence_score NUMERIC(5,2) DEFAULT 84.0, detected_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_recovery (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, complaint_id UUID REFERENCES enterprise_customer_complaints(id) ON DELETE CASCADE, recovery_action TEXT NOT NULL, compensation_amount_usd NUMERIC(10,2) DEFAULT 0.00, status TEXT DEFAULT 'AI_PROPOSED', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_service_dependencies (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, service_name TEXT NOT NULL, dependent_system TEXT NOT NULL, dependency_type TEXT DEFAULT 'CORE_API', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_service_incidents (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, incident_title TEXT NOT NULL, severity TEXT DEFAULT 'SEV_2', duration_minutes NUMERIC(8,2) DEFAULT 35.0, status TEXT DEFAULT 'RESOLVED', occurred_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_service_root_causes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, incident_id UUID REFERENCES enterprise_service_incidents(id) ON DELETE CASCADE, root_cause_category TEXT DEFAULT 'CONFIG_DRIFT', causal_confidence_score NUMERIC(5,2) DEFAULT 89.0, status TEXT DEFAULT 'VERIFIED', analyzed_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_service_automation (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, candidate_name TEXT NOT NULL, deflection_potential_pct NUMERIC(5,2) DEFAULT 38.0, status TEXT DEFAULT 'AI_PROPOSED', evaluated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_experience_scenarios (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, scenario_name TEXT NOT NULL, simulated_csat_delta_pct NUMERIC(5,2) DEFAULT 12.0, status TEXT DEFAULT 'SIMULATED', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_experience_forecasts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, forecast_horizon TEXT DEFAULT '12_MONTHS', projected_case_volume INTEGER DEFAULT 4500, projected_satisfaction_score NUMERIC(5,2) DEFAULT 91.0, status TEXT DEFAULT 'FORECAST', confidence_score NUMERIC(5,2) DEFAULT 88.0, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_customer_experience_traces (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, root_signal_id TEXT NOT NULL, trace_payload JSONB DEFAULT '{}'::jsonb, provenance_hash TEXT NOT NULL, generated_at TIMESTAMPTZ DEFAULT NOW());
