CREATE TABLE IF NOT EXISTS enterprise_treasury_accounts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, tenant_id UUID REFERENCES organizations(id) ON DELETE CASCADE, account_number TEXT NOT NULL, bank_name TEXT NOT NULL, currency TEXT DEFAULT 'USD', account_type TEXT DEFAULT 'OPERATING', status TEXT DEFAULT 'ACTIVE', is_restricted BOOLEAN DEFAULT false, provenance_hash TEXT NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW(), updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_bank_balances (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, account_id UUID REFERENCES enterprise_treasury_accounts(id) ON DELETE CASCADE, reported_balance_usd NUMERIC(16,2) DEFAULT 25000000.00, available_balance_usd NUMERIC(16,2) DEFAULT 22500000.00, ledger_balance_usd NUMERIC(16,2) DEFAULT 25000000.00, balance_date TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_cash_positions (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, consolidated_cash_usd NUMERIC(16,2) DEFAULT 85000000.00, available_liquidity_usd NUMERIC(16,2) DEFAULT 75000000.00, restricted_cash_usd NUMERIC(16,2) DEFAULT 10000000.00, calculated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_cash_pools (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, pool_name TEXT NOT NULL, pool_type TEXT DEFAULT 'PHYSICAL_SWEEPING', total_liquidity_usd NUMERIC(16,2) DEFAULT 45000000.00, status TEXT DEFAULT 'ACTIVE', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_cash_concentrations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, concentration_type TEXT DEFAULT 'BANK_CONCENTRATION', top_counterparty TEXT NOT NULL, concentration_pct NUMERIC(5,2) DEFAULT 42.5, evaluated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_cash_inflows (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, inflow_source TEXT DEFAULT 'COLLECTIONS', amount_usd NUMERIC(14,2) DEFAULT 4500000.00, probability_pct NUMERIC(5,2) DEFAULT 95.0, scheduled_date DATE NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_cash_outflows (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, outflow_category TEXT DEFAULT 'PAYROLL_AND_SUPPLIERS', amount_usd NUMERIC(14,2) DEFAULT 3200000.00, priority TEXT DEFAULT 'MANDATORY', scheduled_date DATE NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_liquidity_buffers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, minimum_operating_cash_usd NUMERIC(16,2) DEFAULT 15000000.00, emergency_buffer_usd NUMERIC(16,2) DEFAULT 10000000.00, actual_buffer_usd NUMERIC(16,2) DEFAULT 28000000.00, evaluated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_liquidity_gaps (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, horizon_weeks INTEGER DEFAULT 4, gap_amount_usd NUMERIC(14,2) DEFAULT 0.00, severity TEXT DEFAULT 'NORMAL', detected_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_debt_instruments (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, instrument_name TEXT NOT NULL, principal_amount_usd NUMERIC(16,2) DEFAULT 50000000.00, interest_rate_pct NUMERIC(5,2) DEFAULT 6.25, maturity_date DATE NOT NULL, status TEXT DEFAULT 'ACTIVE', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_debt_maturities (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, instrument_id UUID REFERENCES enterprise_debt_instruments(id) ON DELETE CASCADE, principal_due_usd NUMERIC(16,2) DEFAULT 50000000.00, due_date DATE NOT NULL, refinancing_risk TEXT DEFAULT 'LOW', evaluated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_credit_facilities (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, facility_name TEXT NOT NULL, committed_limit_usd NUMERIC(16,2) DEFAULT 30000000.00, drawn_amount_usd NUMERIC(16,2) DEFAULT 5000000.00, available_drawing_usd NUMERIC(16,2) DEFAULT 25000000.00, expiry_date DATE NOT NULL, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_treasury_covenants (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, covenant_name TEXT NOT NULL, required_ratio NUMERIC(6,2) DEFAULT 3.00, actual_ratio NUMERIC(6,2) DEFAULT 1.85, headroom_pct NUMERIC(5,2) DEFAULT 38.3, status TEXT DEFAULT 'COMPLIANT', checked_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_intercompany_funding (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, source_entity TEXT NOT NULL, target_entity TEXT NOT NULL, loan_amount_usd NUMERIC(14,2) DEFAULT 5000000.00, interest_rate_pct NUMERIC(5,2) DEFAULT 4.50, status TEXT DEFAULT 'AUTHORIZED', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_cash_transfers (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, source_account_id UUID REFERENCES enterprise_treasury_accounts(id) ON DELETE CASCADE, dest_account_id UUID REFERENCES enterprise_treasury_accounts(id) ON DELETE CASCADE, amount_usd NUMERIC(14,2) DEFAULT 2000000.00, status TEXT DEFAULT 'EXECUTED', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_fx_exposures (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, currency_pair TEXT DEFAULT 'EUR/USD', net_exposure_usd NUMERIC(14,2) DEFAULT 12000000.00, var_95_pct_usd NUMERIC(12,2) DEFAULT 450000.00, evaluated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_fx_scenarios (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, scenario_name TEXT NOT NULL, simulated_fx_shock_pct NUMERIC(5,2) DEFAULT -10.0, simulated_pnl_impact_usd NUMERIC(14,2) DEFAULT -1200000.00, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_treasury_hedges (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, hedge_instrument TEXT DEFAULT 'FX_FORWARD', notional_usd NUMERIC(14,2) DEFAULT 10000000.00, hedge_ratio_pct NUMERIC(5,2) DEFAULT 83.3, status TEXT DEFAULT 'ACTIVE', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_excess_cash (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, total_surplus_usd NUMERIC(16,2) DEFAULT 47000000.00, investable_surplus_usd NUMERIC(16,2) DEFAULT 32000000.00, yield_optimization_bps NUMERIC(5,2) DEFAULT 45.0, evaluated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_treasury_counterparties (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, counterparty_name TEXT NOT NULL, total_exposure_usd NUMERIC(16,2) DEFAULT 35000000.00, credit_rating TEXT DEFAULT 'AA-', status TEXT DEFAULT 'APPROVED', evaluated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_treasury_anomalies (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, anomaly_type TEXT NOT NULL, deviation_pct NUMERIC(5,2) DEFAULT 32.5, severity TEXT DEFAULT 'MEDIUM', status TEXT DEFAULT 'INVESTIGATING', detected_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_treasury_leakage (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, leakage_category TEXT DEFAULT 'IDLE_CASH_INEFFICIENCY', estimated_annual_loss_usd NUMERIC(14,2) DEFAULT 180000.00, status TEXT DEFAULT 'OPPORTUNITY_IDENTIFIED', detected_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_treasury_risks (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, risk_domain TEXT DEFAULT 'LIQUIDITY_GAP', risk_score NUMERIC(5,2) DEFAULT 24.5, status TEXT DEFAULT 'MITIGATED', assessed_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_treasury_stress_tests (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, stress_level TEXT DEFAULT 'SEVERE', survival_horizon_days INTEGER DEFAULT 180, buffer_depletion_pct NUMERIC(5,2) DEFAULT 65.0, evaluated_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_treasury_forecasts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, forecast_horizon TEXT DEFAULT '13_WEEKS', projected_liquidity_usd NUMERIC(16,2) DEFAULT 88000000.00, confidence_score NUMERIC(5,2) DEFAULT 91.0, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_treasury_values (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, projected_yield_improvement_usd NUMERIC(14,2) DEFAULT 450000.00, realized_yield_improvement_usd NUMERIC(14,2) DEFAULT 435000.00, variance_usd NUMERIC(14,2) DEFAULT -15000.00, recorded_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_treasury_drift (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, entity_id UUID NOT NULL, drift_type TEXT NOT NULL, drift_level TEXT DEFAULT 'NO_DRIFT', detected_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_treasury_learning (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, event_type TEXT NOT NULL, description TEXT NOT NULL, append_only BOOLEAN DEFAULT true, created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_treasury_recommendations (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, recommendation_type TEXT NOT NULL, title TEXT NOT NULL, rationale TEXT NOT NULL, confidence_score NUMERIC(5,2) DEFAULT 89.5, status TEXT DEFAULT 'AI_PROPOSED', created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS enterprise_treasury_traces (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), workspace_id UUID REFERENCES workspaces(id) ON DELETE CASCADE, root_signal_id TEXT NOT NULL, trace_payload JSONB DEFAULT '{}'::jsonb, provenance_hash TEXT NOT NULL, generated_at TIMESTAMPTZ DEFAULT NOW());

-- Enable RLS
DO $$
DECLARE
  table_name text;
BEGIN
  FOR table_name IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename LIKE 'enterprise_%'
  LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', table_name);
    EXECUTE format('CREATE INDEX IF NOT EXISTS idx_%I_workspace_id ON %I(workspace_id);', table_name, table_name);
  END LOOP;
END $$;
